version: 2
updates:
  - package-ecosystem: npm
    assignees:
      - cptpiepmatz
    labels: []
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    groups:
      angular:
        patterns:
          - "@angular/*"
      ng-icons:
        patterns:
          - "@ng-icons/*"
