[overview.button.model]
en = "Model"
de = "Modell"

[overview.button.map]
en = "Map"
de = "Karte"

[overview.button.pictures]
en = "Pictures"
de = "Bilder"

[overview.header.daySelection]
en = "Daily Course from"
de = "Tagesverlauf vom"

[overview.header.drainage]
en = "Drainage"
de = "Entwässerung"

[overview.header.features]
en = "Current Values & Properties"
de = "Aktuelle Messwerte & Eigenschaften"

[overview.header.rainForecast]
en = "Rain Forecast"
de = "Regenvorhersage"

[overview.header.waterLevel]
en = "Water Level"
de = "Wasserspiegel"

[overview.draining.yes]
en = "Draining since"
de = "Entwässern seit"

[overview.draining.no]
en = "No draining"
de = "Keine Entwässerung"

[simulation.header.settings]
en = "Parameter Settings"
de = "Parametereinstellungen"

[simulation.settings.currentLevel]
en = "Apply current water level"
de = "Aktuellen Wasserpegel übernehmen"

[simulation.settings.drainage]
en = "Activate drainage rules"
de = "Entwässerungsregeln aktivieren"

[simulation.settings.rainForecast]
en = "Apply current weather forecast"
de = "Aktuelle Wetterprognose übernehmen"

[simulation.settings.startLevel]
en = "Start Level"
de = "Startpegel"

[tab.overview]
en = "Overview"
de = "Übersicht"

[tab.simulation]
en = "Simulation"
de = "Simulation"