[overview.header.features]
en = "Current Values & Properties"
de = "Aktuelle Messwerte & Eigenschaften"

[tab.overview]
en = "Overview"
de = "Übersicht"

[tab.simulation]
en = "Simulation"
de = "Simulation"