[history.header.daySelection]
en = "Daily Course from"
de = "Tagesverlauf vom"

[history.header.drainage]
en = "Drainage"
de = "Entwässerung"

[history.header.waterLevel]
en = "Water Level"
de = "Wasserspiegel"

[overview.button.model]
en = "Model"
de = "Modell"

[overview.button.map]
en = "Map"
de = "Karte"

[overview.button.pictures]
en = "Pictures"
de = "Bilder"

[overview.header.currentValues]
en = "Current Values"
de = "Aktuelle Messwerte"

[overview.header.features]
en = "Features"
de = "Eigenschaften"

[overview.header.rainForecast]
en = "Rain Forecast"
de = "Regenvorhersage"

[overview.draining.yes]
en = "Draining since"
de = "Entwässern seit"

[overview.draining.no]
en = "No draining"
de = "Keine Entwässerung"

[simulation.button.addRule]
en = "Add rule"
de = "Regel hinzufügen"

[simulation.button.simulation]
en = "Start Simulation"
de = "Simulation starten"

[simulation.modal.rainForecast]
en = "Adjust rain forecast"
de = "Regenprognose anpassen"

[simulation.settings.drainage]
en = "Activate drainage rules"
de = "Entwässerungsregeln aktivieren"

[simulation.settings.rainForecast]
en = "Apply rain forecast"
de = "Regenvorhersage übernehmen"

[simulation.settings.rainForecastDate]
en = "Apply forecast from time"
de = "Vorhersage übernehmen vom Zeitpunkt"

[simulation.settings.drainageForerun]
en = "Drainage Forerun"
de = "Entwässerungsvorlauf"

[simulation.settings.rainAmount]
en = "Rain Amount"
de = "Regenmenge"

[simulation.settings.rainDuration]
en = "Rain Duration"
de = "Regendauer"

[simulation.settings.setStartLevel]
en = "Set starting water level"
de = "Startwasserpegel einstellen"

[simulation.settings.targetLevel]
en = "Target Level"
de = "Zielpegel"

[tab.history]
en = "History"
de = "Historie"

[tab.overview]
en = "Overview"
de = "Übersicht"

[tab.simulation]
en = "Simulation"
de = "Simulation"