[overview.button.model]
en = "Model"
de = "Modell"

[overview.button.map]
en = "Map"
de = "Karte"

[overview.button.pictures]
en = "Pictures"
de = "Bilder"

[overview.header.daySelection]
en = "Daily Course from"
de = "Tagesverlauf vom"

[overview.header.drainage]
en = "Drainage"
de = "Entwässerung"

[overview.header.features]
en = "Current Values & Properties"
de = "Aktuelle Messwerte & Eigenschaften"

[overview.header.rainForecast]
en = "Rain Forecast"
de = "Regenvorhersage"

[overview.header.waterLevel]
en = "Water Level"
de = "Wasserspiegel"

[overview.draining.yes]
en = "Draining since"
de = "Entwässern seit"

[overview.draining.no]
en = "No draining"
de = "Keine Entwässerung"

[simulation.button.addRule]
en = "Add rule"
de = "Regel hinzufügen"

[simulation.button.simulation]
en = "Start Simulation"
de = "Simulation starten"

[simulation.header.settings]
en = "Parameter Settings"
de = "Parametereinstellungen"

[simulation.modal.rainForecast]
en = "Adjust rain forecast"
de = "Regenprognose anpassen"

[simulation.settings.waterLevel]
en = "Apply water level"
de = "Wasserpegel übernehmen"

[simulation.settings.drainage]
en = "Activate drainage rules"
de = "Entwässerungsregeln aktivieren"

[simulation.settings.rainForecast]
en = "Apply rain forecast"
de = "Regenprognose übernehmen"

[simulation.settings.drainageForerun]
en = "Drainage Forerun"
de = "Entwässerungsvorlauf"

[simulation.settings.rainAmount]
en = "Rain Amount"
de = "Regenmenge"

[simulation.settings.rainDuration]
en = "Rain Duration"
de = "Regendauer"

[simulation.settings.startLevel]
en = "Start Level"
de = "Startpegel"

[simulation.settings.targetLevel]
en = "Target Level"
de = "Zielpegel"

[tab.overview]
en = "Overview"
de = "Übersicht"

[tab.simulation]
en = "Simulation"
de = "Simulation"