[display.module]
en = "Long-Term Forecast"
de = "Langzeitprognose"

[layer.municipals]
en = "Municipals"
de = "Kommunen"

[layer.counties]
en = "Counties"
de = "Landkreise"

[calc-forecast]
en = "Calculate Forecast"
de = "Berechne Prognose"
