[timeframe.one-day]
en = "one day"
de = "ein Tag"

[timeframe.one-week]
en = "one week"
de = "eine Woche"

[timeframe.one-month]
en = "one month"
de = "ein Monat"

[timeframe.three-months]
en = "three months"
de = "drei Monate"

[timeframe.six-months]
en = "six months"
de = "sechs Monate"

[timeframe.one-year]
en = "one year"
de = "ein Jahr"

[timeframe.all]
en = "whole period"
de = "gesamter Zeitraum"

[resolution.hourly]
en = "hourly"
de = "stündlich"

[resolution.daily]
en = "daily"
de = "täglich"

[resolution.weekly]
en = "weekly"
de = "wöchentlich"

[smartmeter.atypical]
en = "atypical household"
de = "atypischer Haushalt"

[smartmeter.family]
en = "family household"
de = "Familienhaushalt"

[smartmeter.retired]
en = "retired household"
de = "Ruhestandshaushalt"

[smartmeter.single]
en = "single household"
de = "Single Haushalt"

[delete]
en = "Delete Charts"
de = "Lösche Charts"

[choice.smartmeter]
en = "Select Smartmeter"
de = "Wähle Smartmeter"

[choice.timeframe]
en = "Select Timeframe"
de = "Wähle Zeitrahmen"

[choice.resolution]
en = "Select Resolution"
de = "Wähle Auflösung"

[choice.weather]
en = "Select Weather"
de = "Wähle Wetter"

[choice.weatherColumn]
en = "Select Column"
de = "Wähle Spalte"

[request.realdata]
en = "Display Data"
de = "Zeige Daten an"

[request.trainModel]
en = "Train Model"
de = "Modell trainieren"

[request.preddata]
en = "Display predicted data"
de = "Zeige vorhergesagte Daten an"

[graph.mode.line]
en = "Line Chart"
de = "Liniendiagramm"

[graph.mode.bar]
en = "Bar Chart"
de = "Balkendiagramm"

[startpoint.menu]
en = "Start Point"
de = "Startpunkt"

[startpoint.options.a]
en = "Start of Timeseries"
de = "Start der Zeitreihe"

[startpoint.options.b]
en = "Start of June 2021"
de = "Anfang Juni 2021"

[startpoint.options.c]
en = "Start of 2022"
de = "Anfang 2022"

[useWeather.On]
en = "Use Weather Data"
de = "Nutze Wetterdaten"

[useWeather.Off]
en = "Do not use Weather Data"
de = "Nutze keine Wetterdaten"

[metrics.MAE]
en = "Mean Absolute Error"
de = "Mittlerer abs. Fehler"

[metrics.MSE]
en = "Mean Squared Error"
de = "Mittlere quadratische Abweichung"

[metrics.RMSE]
en = "Root Mean Squared Error"
de = "Wurzel des mittleren quadratischen Fehlers"

[weather.air_temperature]
en = "Temperature"
de = "Temperatur"

[weather.precipitation]
en = "Precipitation"
de = "Niederschlag"

[weather.moisture]
en = "Moisture"
de = "Feuchtigkeit"

[weather.plain]
en = "No Weather"
de = "Kein Wetter"
