[lang] # the currently selected language
en = "English"
de = "Deutsch"

[langs.english] # labels for english language
en = "English"
de = "Englisch"

[langs.german] # labels for german language
en = "German"
de = "Deutsch"

[login]
en = "Login"
de = "Anmelden"

[logout]
en = "Logout"
de = "Abmelden"
