[titles.chart]
en = "Predicted Water Consumption"
de = "Vorhergesagter Wasserverbrauch"

[titles.model_select]
en = "Model Selection for Prediction"
de = "Modellauswahl für Vorhersage"

[titles.model_train]
en = "Model Training"
de = "Modell Training"

[titles.smart_meter]
en = "List of Smartmeters"
de = "Liste von Smartmetern"

[titles.virtual_meter]
en = "List of virtual Smartmeters"
de = "Liste von virtuellen Smartmetern"

[buttons.forecast]
en = "Create Forecast"
de = "Mache Vorhersage"

[buttons.model_train]
en = "Train Model"
de = "Trainiere Modell"

[tables.name]
en = "Name"
de = "Name"

[tables.date]
en = "Date"
de = "Datum"

[tables.locality]
en = "City"
de = "Stadt"

[tables.address]
en = "Address"
de = "Adresse"

[tables.submeters]
en = "SubMeters"
de = "SubMeter"

[tables.supermeters]
en = "SuperMeters"
de = "SuperMeter"

[model_training.algorithm]
en = "Algorithm"
de = "Algorithmus"

[model_training.virtual_meter]
en = "Virtual Meter"
de = "Virtuelles Smartmeter"

[model_training.comment]
en = "Comment"
de = "Kommentar"

[no_data]
en = "No data available"
de = "Keine Daten verfügbar"