[titles.chart]
en = "Predicted Water Consumption"
de = "Vorhergesagter Wasserverbrauch"

[titles.model_select]
en = "Model Selection for Prediction"
de = "Modellauswahl für Vorhersage"

[titles.model_train]
en = "Model Training"
de = "Modell Training"

[titles.smart_meter]
en = "List of Smartmeters"
de = "Liste von Smartmetern"

[titles.virtual_meter]
en = "List of Virtual Meters"
de = "Liste von Virtual Metern"

[buttons.forecast]
en = "Create Forecast"
de = "Mache Vorhersage"

[buttons.model_train]
en = "Train Model"
de = "Trainiere Modell"

[tables.name]
en = "Name"
de = "Name"

[tables.date]
en = "Date"
de = "Datum"

[tables.locality]
en = "City"
de = "Stadt"

[tables.address]
en = "Address"
de = "Adresse"

[tables.submeters]
en = "Submeters"
de = "Submeter"

[tables.supermeters]
en = "Supermeters"
de = "Supermeter"

[model_training.algorithm]
en = "Algorithm"
de = "Algorithmus"

[model_training.virtual_meter]
en = "Virtual Meter"
de = "Virtual Meter"

[model_training.comment]
en = "Comment"
de = "Kommentar"

[hints.algorithm]
en = "Select Algorithm"
de = "Algorithmus auswählen"

[hints.virtual_meter]
en = "Select Virtual Meter"
de = "Virtual Meter auswählen"

[hints.virtual_meter_name]
en = "Enter Virtual Meter Name"
de = "Virtual Meter Namen eingeben"

[hints.supermeter_name]
en = "Enter Supermeter Name"
de = "Supermeter Namen eingeben"

[hints.comment]
en = "Add a comment"
de = "Kommentar hinzufügen"

[no_data]
en = "No data available"
de = "Keine Daten verfügbar"
