name: continuous-integration

on:
  push:

jobs:
  install:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev

  npm:
    name: npm ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    needs: install
    continue-on-error: ${{ matrix.job.error }}

    strategy:
      matrix:
        job:
          - name: build
            command: npm run build
            error: false
          - name: lint
            command: npm run lint -- --deny-warnings
            error: true
          - name: doc
            command: npm run doc
            error: true
          - name: fmt
            command: npx prettier . --check --plugin prettier-plugin-toml
            error: true
          - name: test
            command: npm run test
            error: false

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: ${{ matrix.job.command }}
