name: continuous-integration

on:
  push:

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev

  npm:
    name: ${{ matrix.job.name }}
    runs-on: ${{ matrix.job.runs-on || 'ubuntu-latest' }}
    needs: install
    continue-on-error: ${{ matrix.job.continue-on-error || false }}

    strategy:
      matrix:
        job:
          - name: build
            command: npm run build
          - name: lint
            command: npm run lint -- --deny-warnings
            continue-on-error: true
          - name: doc
            command: npm run doc
            continue-on-error: true
          - name: fmt
            command: npx prettier . --check --plugin prettier-plugin-toml
            continue-on-error: true
          - name: test
            command: npm run test
          - name: e2e (linux)
            command: |
              npx playwright install --with-deps chromium firefox
              xvfb-run --auto-servernum npm run e2e
          - name: e2e (windows)
            command: |
              npx playwright install --with-deps chromium firefox
              npm run e2e
            runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: ${{ matrix.job.command }}
      - uses: actions/upload-artifact@v4
        if: always() && startsWith(matrix.job.name, 'e2e')
        with:
          name: playwright-test-results-${{ matrix.job.name }}
          path: test-results/
          if-no-files-found: ignore
