name: continous-integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npm run build
    
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npm run lint

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npm run docs
