name: continous-integration

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npm run build

  lint:
    needs: install
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npm run lint -- --deny-warnings

  doc:
    # verify that documentation can be built, will be moved to own pipeline
    # once new documentation setup is done
    needs: install
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npm run doc

  fmt:
    needs: install
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --include dev
      - run: npx prettier . --check --plugin prettier-plugin-toml
