name: docker
on:
  workflow_dispatch:
  push:
    branches:
      # build for every branch push
      - "**"
    tags:
      # Build for semver formatted tags
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - id: checkout
        name: Checkout Build Sources
        uses: actions/checkout@v4

      - uses: wisdom-oss/actions/docker-build/multiplatform/build@main
        name:
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          target-platform: ${{ matrix.platforms }}

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: wisdom-oss/actions/docker-build/multiplatform/merge@main
        name:
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev:
    environment: dev
    runs-on: self-hosted
    if: (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) && github.event_name == 'push'
    needs:
      - merge
    steps: &deploymentSteps
      - name: setup-ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.HOSTNAME }} > ~/.ssh/known_hosts

      - name: pull-image
        run: ssh ${{ secrets.USERNAME }}@${{ vars.HOSTNAME }} "FRONTEND_VERSION='${{ github.ref_name }}' docker compose pull frontend"

      - name: restart-container
        run: ssh ${{ secrets.USERNAME }}@${{ vars.HOSTNAME }} "FRONTEND_VERSION='${{ github.ref_name }}' docker compose up -d frontend"

  deploy-demo:
    environment: demo
    runs-on: self-hosted
    if: (github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) && github.event_name == 'push'
    steps: *deploymentSteps

  deploy-live:
    environment: live
    runs-on: self-hosted
    if: (github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) && github.event_name == 'push'
    steps: *deploymentSteps
